# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9edef2b482d96d2cd8b16c65aa28b6e27ca2ca91d34aad0579f0785c25334b1f7b5e43807e02085532c77a0cc88541c2a64e8e72c1a595018b51b34224fe6588

test:
  secret_key_base: c493e194db49c6965fe7cb62eb82c8b380fc750cb2043a08542b7e2147fc67018cda7c95be2625021c195b940c4fbdd4d11b755f5f628262f0ba89d98ecbe511

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
